# Generated by Django 6.0.5 on 2026-05-15 12:45

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import test_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=35)),
                ('pseudonym', models.CharField(max_length=20)),
                ('bio', models.TextField(null=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('na', 'N/A')], default='na', max_length=4)),
                ('email', models.EmailField(max_length=75, null=True)),
                ('website', models.URLField(null=True)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('followers_count', models.PositiveIntegerField(null=True)),
                ('posts_count', models.PositiveIntegerField(null=True)),
                ('comments_count', models.PositiveIntegerField(null=True)),
                ('reputation_score', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('monetisation_income', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique_for_month='posted_at')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_time', models.DurationField(null=True)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('email', models.EmailField(blank=True, max_length=80, null=True, unique=True, verbose_name='Email')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('role', models.CharField(choices=[('admin', 'ADMIN'), ('moderator', 'MODERATOR'), ('lib-member', 'LIB_MEMBER')], default='lib-member', max_length=25, verbose_name='Role')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('na', 'N/A')], default='na', max_length=25, verbose_name='Gender')),
                ('phone', models.CharField(blank=True, max_length=75, null=True, unique=True, validators=[test_app.models.validate_phone_number], verbose_name='Phone')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(120)], verbose_name='Age')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is Staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('verified', models.BooleanField(default=False, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='You must provide specific name of book', max_length=100, unique=True, verbose_name='Book name')),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, choices=[('en', 'English'), ('ua', 'Ukrainian'), ('de', 'German')], max_length=30, null=True)),
                ('genre', models.CharField(blank=True, choices=[('fiction', 'Fiction'), ('triller', 'Triller')], max_length=30, null=True)),
                ('price', models.FloatField()),
                ('discounted_price', models.FloatField(null=True)),
                ('published_date', models.DateField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='test_app.author')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BOOK',
                'verbose_name_plural': 'BOOKS',
                'db_table': 'books',
                'ordering': ['-published_date', 'title'],
                'get_latest_by': 'published_date',
                'indexes': [models.Index(fields=['genre', 'language'], name='books_genre_language_idx')],
                'constraints': [models.UniqueConstraint(fields=('title', 'author'), name='books_title_author_uqcst')],
            },
        ),
    ]
