# Generated by Django 6.0.5 on 2026-05-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_book_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'get_latest_by': 'published_date', 'ordering': ['-published_date', 'title'], 'verbose_name': 'BOOK', 'verbose_name_plural': 'BOOKS'},
        ),
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('na', 'N/A')], default='na', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('fiction', 'Fiction'), ('triller', 'Triller')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ua', 'Ukrainian'), ('de', 'German')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, unique_for_date='created_at'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['genre', 'language'], name='books_genre_language_idx'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='books_title_author_uqcst'),
        ),
        migrations.AlterModelTable(
            name='author',
            table='authors',
        ),
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
